### ISSUE TITLE
Where are 'epoch_file' and 'metrics_file'?

### ISSUE THREAD

**Issue by qinwei-hfut** [dspoka/mnm#1]
Hi, when I run the code,  the program cannot find the 'epoch_file' and the 'metrics_file'. Those two variables seem to mean how to split the dataset. But I can not find the related functions and don't know how to generate those files. Could you help me with this issue? Thank you.

**Comment by dspoka** [comment]
Hey sorry about that, linked the data tar. Could have sworn it was somehow linked before.
